# デフォルトで読み込む設定グループを指定
defaults:
  - paths: default
  - dataset: dair-ai
  - embedding: bert
  - cebra: offset1-model
  - consistency_check: default
  - hpt: my_sweep
  - _self_

device: ${oc.env:DEVICE, cpu}

reproducibility:
  seed: 42
  deterministic: false
  cudnn_benchmark: false

hydra:
  run:

    dir: results/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}

evaluation:
  test_size: 0.2
  random_state: 42
  knn_neighbors: 5
  enable_plots: false

reproducibility:
  seed: ${evaluation.random_state}
  deterministic: false

wandb:
  project: "CEBRA_NLP_Experiment-${dataset.name}"
  run_name: "default_run"
  entity: null
# secrets:
#   aws_access_key_id: ${oc.env:AWS_ACCESS_KEY_ID}
#   aws_secret_access_key: ${oc.env:AWS_SECRET_ACCESS_KEY}
#   endpoint_url: ${oc.env:MLFLOW_S3_ENDPOINT_URL, http://localhost:9000}
#   region: ${oc.env:AWS_DEFAULT_REGION, us-east-1}
#   s3_signature_version: ${oc.env:AWS_S3_SIGNATURE_VERSION, s3v4}
ddp:
  world_size: 1
  rank: 0
  local_rank: 0
